const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Clipboard,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{"8Direções": 0},
	{BoundTo: 0},
	{Piscar: 0},
	{nave: 0},
	{Rotate: 0},
	{Bullet: 0},
	{meteoro: 0},
	{Sprite: 0},
	{spawner: 0},
	{recorde: 0},
	{Text2: 0},
	{Text3: 0},
	{TextInput: 0},
	{Text4: 0},
	{Sprite2: 0},
	{Clipboard: 0},
	{Sprite3: 0},
	{barradevida: 0},
	{Sprite4: 0},
	{TextoTempo: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{gameover: 0},
	{play: 0},
	{vida: 0},
	{Sprite7: 0},
	{Text: 0},
	{Keyboard: 0},
	{Sprite8: 0},
	{Text5: 0},
	{Text6: 0},
	{Sprite9: 0},
	{Áudio: 0},
	{Vida: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	nave: class extends self.ISpriteInstance {},
	meteoro: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	spawner: class extends self.ISpriteInstance {},
	recorde: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Clipboard: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	barradevida: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TextoTempo: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	vida: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {}
}